
package com.you07.cas.ruijie.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.math.BigDecimal;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SamServicePortType", targetNamespace = "http://api.spl.ruijie.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SamServicePortType {


    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryRepairReportResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRepairReport", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryRepairReport")
    @ResponseWrapper(localName = "queryRepairReportResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryRepairReportResponse")
    public QueryRepairReportResult queryRepairReport(
            @WebParam(name = "params", targetNamespace = "")
                    QueryRepairReportParam params);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.FindOnlineStateResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOnlineState", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindOnlineState")
    @ResponseWrapper(localName = "findOnlineStateResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindOnlineStateResponse")
    public FindOnlineStateResult findOnlineState(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.ResumeUserResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resumeUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ResumeUser")
    @ResponseWrapper(localName = "resumeUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ResumeUserResponse")
    public ResumeUserResult resumeUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param password
     * @return
     *     returns com.wifi.client.EncryptPasswordResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "encryptPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.EncryptPassword")
    @ResponseWrapper(localName = "encryptPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.EncryptPasswordResponse")
    public EncryptPasswordResult encryptPassword(
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTxid", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.CreateTxid")
    @ResponseWrapper(localName = "createTxidResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.CreateTxidResponse")
    public String createTxid();

    /**
     * 
     * @param queryLoginFailLogParams
     * @return
     *     returns com.wifi.client.QueryLoginFailLogResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryLoginFailLog", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryLoginFailLog")
    @ResponseWrapper(localName = "queryLoginFailLogResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryLoginFailLogResponse")
    public QueryLoginFailLogResult queryLoginFailLog(
            @WebParam(name = "queryLoginFailLogParams", targetNamespace = "")
                    QueryLoginFailLogParams queryLoginFailLogParams);

    /**
     * 
     * @param queryOnlineDetailParams
     * @return
     *     returns com.wifi.client.QueryOnlineDetailResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineDetail", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineDetail")
    @ResponseWrapper(localName = "queryOnlineDetailResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineDetailResponse")
    public QueryOnlineDetailResult queryOnlineDetail(
            @WebParam(name = "queryOnlineDetailParams", targetNamespace = "")
                    QueryOnlineDetailParams queryOnlineDetailParams);

    /**
     * 
     * @param queryOnlineDetailParams
     * @return
     *     returns com.wifi.client.QueryOnlineDetailResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineDetailV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineDetailV2")
    @ResponseWrapper(localName = "queryOnlineDetailResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineDetailResponseV2")
    public QueryOnlineDetailResultV2 queryOnlineDetailV2(
            @WebParam(name = "queryOnlineDetailParams", targetNamespace = "")
                    QueryOnlineDetailParams queryOnlineDetailParams);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.FindFlowDescInfoResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFlowDescInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindFlowDescInfo")
    @ResponseWrapper(localName = "findFlowDescInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindFlowDescInfoResponse")
    public FindFlowDescInfoResult findFlowDescInfo(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param ftpServerPort
     * @param ftpServerIp
     * @param ftpPass
     * @param ftpUser
     * @param ftpBakPath
     * @param exportTables
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveFtpExport", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SaveFtpExport")
    @ResponseWrapper(localName = "saveFtpExportResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SaveFtpExportResponse")
    public SamApiBaseResult saveFtpExport(
            @WebParam(name = "ftpServerIp", targetNamespace = "")
                    String ftpServerIp,
            @WebParam(name = "ftpServerPort", targetNamespace = "")
                    Long ftpServerPort,
            @WebParam(name = "ftpBakPath", targetNamespace = "")
                    String ftpBakPath,
            @WebParam(name = "ftpUser", targetNamespace = "")
                    String ftpUser,
            @WebParam(name = "ftpPass", targetNamespace = "")
                    String ftpPass,
            @WebParam(name = "exportTables", targetNamespace = "")
                    List<String> exportTables);

    /**
     * 
     * @return
     *     returns com.wifi.client.FindFtpExportResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findFtpExport", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindFtpExport")
    @ResponseWrapper(localName = "findFtpExportResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindFtpExportResponse")
    public FindFtpExportResult findFtpExport();

    /**
     * 
     * @param fee
     * @param userId
     * @param txid
     * @param refundType
     * @return
     *     returns com.wifi.client.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "refund", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.Refund")
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RefundResponse")
    public AccountOperationResult refund(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "refundType", targetNamespace = "")
                    int refundType,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param fee
     * @param userId
     * @param txid
     * @param fundType
     * @return
     *     returns com.wifi.client.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fund", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.Fund")
    @ResponseWrapper(localName = "fundResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FundResponse")
    public AccountOperationResult fund(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "fundType", targetNamespace = "")
                    int fundType,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param fee
     * @param tradeInfo
     * @param userId
     * @param txid
     * @param fundType
     * @return
     *     returns com.wifi.client.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bankFund", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BankFund")
    @ResponseWrapper(localName = "bankFundResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BankFundResponse")
    public AccountOperationResult bankFund(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "fundType", targetNamespace = "")
                    int fundType,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid,
            @WebParam(name = "tradeInfo", targetNamespace = "")
                    TradeInfo tradeInfo);

    /**
     * 
     * @param fileLicenseDb
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addLicense", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddLicense")
    @ResponseWrapper(localName = "addLicenseResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddLicenseResponse")
    public SamApiBaseResult addLicense(
            @WebParam(name = "fileLicenseDb", targetNamespace = "")
                    FileLicenseDb fileLicenseDb);

    /**
     * 
     * @param name
     * @return
     *     returns com.wifi.client.QueryLicenseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryLicense", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryLicense")
    @ResponseWrapper(localName = "queryLicenseResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryLicenseResponse")
    public QueryLicenseResult queryLicense(
            @WebParam(name = "name", targetNamespace = "")
                    String name);

    /**
     * 
     * @param fileLicenseDb
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delLicense", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DelLicense")
    @ResponseWrapper(localName = "delLicenseResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DelLicenseResponse")
    public SamApiBaseResult delLicense(
            @WebParam(name = "fileLicenseDb", targetNamespace = "")
                    FileLicenseDb fileLicenseDb);

    /**
     * 
     * @param cardNo
     * @param chargeCardType
     * @param userId
     * @param txid
     * @param password
     * @return
     *     returns com.wifi.client.AccountOperationResult
     */
    @WebMethod(operationName = "ChargeCard")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ChargeCard", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ChargeCard")
    @ResponseWrapper(localName = "ChargeCardResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ChargeCardResponse")
    public AccountOperationResult chargeCard(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "chargeCardType", targetNamespace = "")
                    String chargeCardType,
            @WebParam(name = "cardNo", targetNamespace = "")
                    String cardNo,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param fee
     * @param userId
     * @param txid
     * @return
     *     returns com.wifi.client.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "preAccountFeeTransfer", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.PreAccountFeeTransfer")
    @ResponseWrapper(localName = "preAccountFeeTransferResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.PreAccountFeeTransferResponse")
    public AccountOperationResult preAccountFeeTransfer(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "fee", targetNamespace = "")
                    BigDecimal fee,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param txid
     * @return
     *     returns com.wifi.client.QueryTxidResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findExistTxCommand", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindExistTxCommand")
    @ResponseWrapper(localName = "findExistTxCommandResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindExistTxCommandResponse")
    public QueryTxidResult findExistTxCommand(
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param userId
     * @param value
     * @param type
     * @return
     *     returns com.wifi.client.CompensatePeriodBillResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compensatePeriodBill", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.CompensatePeriodBill")
    @ResponseWrapper(localName = "compensatePeriodBillResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.CompensatePeriodBillResponse")
    public CompensatePeriodBillResult compensatePeriodBill(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "type", targetNamespace = "")
                    int type,
            @WebParam(name = "value", targetNamespace = "")
                    BigDecimal value);

    /**
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyPassword")
    @ResponseWrapper(localName = "verifyPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyPasswordResponse")
    public SamApiBaseResult verifyPassword(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyAuthenResult", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyAuthenResult")
    @ResponseWrapper(localName = "verifyAuthenResultResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyAuthenResultResponse")
    public SamApiBaseResult verifyAuthenResult(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SuspendUser")
    @ResponseWrapper(localName = "suspendUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SuspendUserResponse")
    public SamApiBaseResult suspendUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryNtdFlowResult
     */
    @WebMethod
    @WebResult(name = "queryNtdFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryNtdFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryNtdFlow")
    @ResponseWrapper(localName = "queryNtdFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryNtdFlowResponse")
    public QueryNtdFlowResult queryNtdFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryNtdFlowParams params);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.QueryUserPolicyInfoChangeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryUserPolicyInfoChange", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryUserPolicyInfoChange")
    @ResponseWrapper(localName = "queryUserPolicyInfoChangeResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryUserPolicyInfoChangeResponse")
    public QueryUserPolicyInfoChangeResult queryUserPolicyInfoChange(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.wifi.client.VerifyLoginByAccountTypeResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyLoginByAccountType", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyLoginByAccountType")
    @ResponseWrapper(localName = "verifyLoginByAccountTypeResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyLoginByAccountTypeResponse")
    public VerifyLoginByAccountTypeResult verifyLoginByAccountType(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param operatorName
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @return
     *     returns com.wifi.client.BindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOperatorForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BindOperatorForSelf")
    @ResponseWrapper(localName = "bindOperatorForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BindOperatorForSelfResponse")
    public BindOperatorForSelfResult bindOperatorForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param compusName
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "noticeReceiveFileFromCampus", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.NoticeReceiveFileFromCampus")
    @ResponseWrapper(localName = "noticeReceiveFileFromCampusResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.NoticeReceiveFileFromCampusResponse")
    public SamApiBaseResult noticeReceiveFileFromCampus(
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName);

    /**
     * 
     * @param port
     * @param compusName
     * @param actType
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "noticeReceiveFile", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.NoticeReceiveFile")
    @ResponseWrapper(localName = "noticeReceiveFileResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.NoticeReceiveFileResponse")
    public SamApiBaseResult noticeReceiveFile(
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName,
            @WebParam(name = "actType", targetNamespace = "")
                    String actType,
            @WebParam(name = "port", targetNamespace = "")
                    int port);

    /**
     * 
     * @param blackListMessage
     * @param userId
     * @param blackListExpireTime
     * @param blackListFlag
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kickOnlineUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.KickOnlineUser")
    @ResponseWrapper(localName = "kickOnlineUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.KickOnlineUserResponse")
    public SamApiBaseResult kickOnlineUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "blackListFlag", targetNamespace = "")
                    int blackListFlag,
            @WebParam(name = "blackListExpireTime", targetNamespace = "")
                    int blackListExpireTime,
            @WebParam(name = "blackListMessage", targetNamespace = "")
                    String blackListMessage);

    /**
     * 
     * @return
     *     returns com.wifi.client.FindSelfServPermResult
     */
    @WebMethod
    @WebResult(name = "findSelfServPermResult", targetNamespace = "")
    @RequestWrapper(localName = "findSelfServPerm", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindSelfServPerm")
    @ResponseWrapper(localName = "findSelfServPermResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindSelfServPermResponse")
    public FindSelfServPermResult findSelfServPerm();

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryAccountFlowResult
     */
    @WebMethod
    @WebResult(name = "queryAccountFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryAccountFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryAccountFlow")
    @ResponseWrapper(localName = "queryAccountFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryAccountFlowResponse")
    public QueryAccountFlowResult queryAccountFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryAccountFlowParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryUsedFreeFlowResult
     */
    @WebMethod
    @WebResult(name = "queryUsedFreeFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryUsedFreeFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryUsedFreeFlow")
    @ResponseWrapper(localName = "queryUsedFreeFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryUsedFreeFlowResponse")
    public QueryUsedFreeFlowResult queryUsedFreeFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryUsedFreeFlowParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryAccountFlowResult
     */
    @WebMethod
    @WebResult(name = "queryAccountFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryAccountFlowAll", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryAccountFlowAll")
    @ResponseWrapper(localName = "queryAccountFlowAllResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryAccountFlowAllResponse")
    public QueryAccountFlowResult queryAccountFlowAll(
            @WebParam(name = "params", targetNamespace = "")
                    QueryAccountFlowAllParams params);

    /**
     * 
     * @param operatorName
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @return
     *     returns com.wifi.client.BindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOperatorV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BindOperatorV2")
    @ResponseWrapper(localName = "bindOperatorV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BindOperatorV2Response")
    public BindOperatorForSelfResult bindOperatorV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param operatorName
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @return
     *     returns com.wifi.client.ReBindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperatorV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorV2")
    @ResponseWrapper(localName = "rebindOperatorV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorV2Response")
    public ReBindOperatorForSelfResult rebindOperatorV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.FindPeriodicPaymentAmountForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findPeriodicPaymentAmountByUserId", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindPeriodicPaymentAmountByUserId")
    @ResponseWrapper(localName = "findPeriodicPaymentAmountByUserIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindPeriodicPaymentAmountByUserIdResponse")
    public FindPeriodicPaymentAmountForSelfResult findPeriodicPaymentAmountByUserId(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryBankAccountFlowResult
     */
    @WebMethod
    @WebResult(name = "queryBankAccountFlowResult", targetNamespace = "")
    @RequestWrapper(localName = "queryBankAccountFlow", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryBankAccountFlow")
    @ResponseWrapper(localName = "queryBankAccountFlowResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryBankAccountFlowResponse")
    public QueryBankAccountFlowResult queryBankAccountFlow(
            @WebParam(name = "params", targetNamespace = "")
                    QueryBankAccountFlowParams params);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.VerifyPeriodStrategyUserResult
     */
    @WebMethod
    @WebResult(name = "verifyPeriodStrategyUserResult", targetNamespace = "")
    @RequestWrapper(localName = "verifyPeriodStrategyUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyPeriodStrategyUser")
    @ResponseWrapper(localName = "verifyPeriodStrategyUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyPeriodStrategyUserResponse")
    public VerifyPeriodStrategyUserResult verifyPeriodStrategyUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @param userPackageName
     * @param operationTimeType
     * @param templateName
     * @return
     *     returns com.wifi.client.ModifyPackageConfirmInfosResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyPackageConfirmInfos", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyPackageConfirmInfos")
    @ResponseWrapper(localName = "modifyPackageConfirmInfosResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyPackageConfirmInfosResponse")
    public ModifyPackageConfirmInfosResult modifyPackageConfirmInfos(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "templateName", targetNamespace = "")
                    String templateName,
            @WebParam(name = "userPackageName", targetNamespace = "")
                    String userPackageName,
            @WebParam(name = "operationTimeType", targetNamespace = "")
                    short operationTimeType);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.QueryUserResult
     */
    @WebMethod
    @WebResult(name = "queryUserResult", targetNamespace = "")
    @RequestWrapper(localName = "queryUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryUser")
    @ResponseWrapper(localName = "queryUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryUserResponse")
    public QueryUserResult queryUser(
            @WebParam(name = "params", targetNamespace = "")
                    QueryUserParams params);

    /**
     * 
     * @param userTemplateName
     * @param userId
     * @param userPackageName
     * @param operationTimeType
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserPackage", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserPackage")
    @ResponseWrapper(localName = "modifyUserPackageResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserPackageResponse")
    public SamApiBaseResult modifyUserPackage(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "userTemplateName", targetNamespace = "")
                    String userTemplateName,
            @WebParam(name = "userPackageName", targetNamespace = "")
                    String userPackageName,
            @WebParam(name = "operationTimeType", targetNamespace = "")
                    int operationTimeType);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "logicDelUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.LogicDelUser")
    @ResponseWrapper(localName = "logicDelUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.LogicDelUserResponse")
    public SamApiBaseResult logicDelUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyPassword")
    @ResponseWrapper(localName = "modifyPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyPasswordResponse")
    public SamApiBaseResult modifyPassword(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperatorForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorForSelf")
    @ResponseWrapper(localName = "unbindOperatorForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorForSelfResponse")
    public SamApiBaseResult unbindOperatorForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param operatorName
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userSelfReset", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UserSelfReset")
    @ResponseWrapper(localName = "userSelfResetResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UserSelfResetResponse")
    public SamApiBaseResult userSelfReset(
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param cardNo
     * @param chargeCardType
     * @param userId
     * @param txid
     * @param password
     * @return
     *     returns com.wifi.client.AccountOperationResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "chargeCardForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ChargeCardForSelf")
    @ResponseWrapper(localName = "chargeCardForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ChargeCardForSelfResponse")
    public AccountOperationResult chargeCardForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "chargeCardType", targetNamespace = "")
                    String chargeCardType,
            @WebParam(name = "cardNo", targetNamespace = "")
                    String cardNo,
            @WebParam(name = "password", targetNamespace = "")
                    String password,
            @WebParam(name = "txid", targetNamespace = "")
                    String txid);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserResponse")
    public SamApiBaseResult addUser(
            @WebParam(name = "params", targetNamespace = "")
                    AddUserParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserAndBindOperatorUserInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserAndBindOperatorUserInfo")
    @ResponseWrapper(localName = "addUserAndBindOperatorUserInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserAndBindOperatorUserInfoResponse")
    public SamApiBaseResult addUserAndBindOperatorUserInfo(
            @WebParam(name = "params", targetNamespace = "")
                    AddUserAndBindOperatorUserInfoParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserAndBindOperatorNew", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserAndBindOperatorNew")
    @ResponseWrapper(localName = "addUserAndBindOperatorNewResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserAndBindOperatorNewResponse")
    public SamApiBaseResult addUserAndBindOperatorNew(
            @WebParam(name = "params", targetNamespace = "")
                    AddUserAndBindOperatorNewParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addOrUpDateUserInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddOrUpDateUserInfo")
    @ResponseWrapper(localName = "addOrUpDateUserInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddOrUpDateUserInfoResponse")
    public SamApiBaseResult addOrUpDateUserInfo(
            @WebParam(name = "params", targetNamespace = "")
                    AddOrUpDateUserInfoParams params);

    /**
     * 
     * @param groupId
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserGroup", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserGroup")
    @ResponseWrapper(localName = "modifyUserGroupResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserGroupResponse")
    public SamApiBaseResult modifyUserGroup(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "groupId", targetNamespace = "")
                    String groupId);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "regUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RegUser")
    @ResponseWrapper(localName = "regUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RegUserResponse")
    public SamApiBaseResult regUser(
            @WebParam(name = "params", targetNamespace = "")
                    RegUserParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUser")
    @ResponseWrapper(localName = "modifyUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserResponse")
    public SamApiBaseResult modifyUser(
            @WebParam(name = "params", targetNamespace = "")
                    ModifyUserParams params);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DelUser")
    @ResponseWrapper(localName = "delUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DelUserResponse")
    public SamApiBaseResult delUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @return
     *     returns com.wifi.client.QueryAllCustomFieldResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllCustomFieldForUserinfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindAllCustomFieldForUserinfo")
    @ResponseWrapper(localName = "findAllCustomFieldForUserinfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindAllCustomFieldForUserinfoResponse")
    public QueryAllCustomFieldResult findAllCustomFieldForUserinfo();

    /**
     * 
     * @param message
     * @param userId
     * @param messageType
     * @return
     *     returns com.wifi.client.SendMessageResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SendMessageResponse")
    public SendMessageResult sendMessage(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "message", targetNamespace = "")
                    String message,
            @WebParam(name = "messageType", targetNamespace = "")
                    int messageType);

    /**
     * 
     * @param userId
     * @param password
     * @return
     *     returns com.wifi.client.VerifyManagerPasswordResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyManagerPassword", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyManagerPassword")
    @ResponseWrapper(localName = "verifyManagerPasswordResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.VerifyManagerPasswordResponse")
    public VerifyManagerPasswordResult verifyManagerPassword(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "password", targetNamespace = "")
                    String password);

    /**
     * 
     * @param operatorName
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @return
     *     returns com.wifi.client.ReBindOperatorForSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperatorForSlef", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorForSlef")
    @ResponseWrapper(localName = "rebindOperatorForSlefResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorForSlefResponse")
    public ReBindOperatorForSelfResult rebindOperatorForSlef(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.QueryPermissionListForPhoneSelfResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryPermissionListForPhoneSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryPermissionListForPhoneSelf")
    @ResponseWrapper(localName = "queryPermissionListForPhoneSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryPermissionListForPhoneSelfResponse")
    public QueryPermissionListForPhoneSelfResult queryPermissionListForPhoneSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserBindInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UpdateUserBindInfo")
    @ResponseWrapper(localName = "updateBindInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UpdateBindInfoResponse")
    public SamApiBaseResult updateUserBindInfo(
            @WebParam(name = "params", targetNamespace = "")
                    SpiUserBindInfo params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUserBindInfoV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UpdateUserBindInfoV2")
    @ResponseWrapper(localName = "updateBindInfoV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UpdateBindInfoV2Response")
    public SamApiBaseResult updateUserBindInfoV2(
            @WebParam(name = "params", targetNamespace = "")
                    SpiUserBindInfoV2 params);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reLogicDelUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ReLogicDelUser")
    @ResponseWrapper(localName = "reLogicDelUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ReLogicDelUserResponse")
    public SamApiBaseResult reLogicDelUser(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param param
     * @return
     *     returns com.wifi.client.QueryOnlineUserResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineUser", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineUser")
    @ResponseWrapper(localName = "queryOnlineUserResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineUserResponse")
    public QueryOnlineUserResult queryOnlineUser(
            @WebParam(name = "param", targetNamespace = "")
                    QueryOnlineUserParam param);

    /**
     * 
     * @param param
     * @return
     *     returns com.wifi.client.QueryOnlineUserResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryOnlineUserV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineUserV2")
    @ResponseWrapper(localName = "queryOnlineUserResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryOnlineUserResponseV2")
    public QueryOnlineUserResultV2 queryOnlineUserV2(
            @WebParam(name = "param", targetNamespace = "")
                    QueryOnlineUserParam param);

    /**
     * 
     * @return
     *     returns com.wifi.client.FindOnlineUserCountResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findOnlineUserCount", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindOnlineUserCount")
    @ResponseWrapper(localName = "findOnlineUserCountResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindOnlineUserCountResponse")
    public FindOnlineUserCountResult findOnlineUserCount();

    /**
     * 
     * @param spiUserBindInfo
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserBindInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserBindInfo")
    @ResponseWrapper(localName = "addUserBindInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserBindInfoResponse")
    public SamApiBaseResult addUserBindInfo(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "spiUserBindInfo", targetNamespace = "")
                    SpiUserBindInfo spiUserBindInfo);

    /**
     * 
     * @param userId
     * @param spiUserBindInfoV2
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUserBindInfoV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserBindInfoV2")
    @ResponseWrapper(localName = "addUserBindInfoResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddUserBindInfoResponseV2")
    public SamApiBaseResult addUserBindInfoV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "spiUserBindInfoV2", targetNamespace = "")
                    SpiUserBindInfoV2 spiUserBindInfoV2);

    /**
     * 
     * @param userBindInfoUuid
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUserBindInfo", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DeleteUserBindInfo")
    @ResponseWrapper(localName = "deleteUserBindInfoResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DeleteUserBindInfoResponse")
    public SamApiBaseResult deleteUserBindInfo(
            @WebParam(name = "userBindInfoUuid", targetNamespace = "")
                    String userBindInfoUuid);

    /**
     * 
     * @return
     *     returns com.wifi.client.FindAllUserGroupsResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUserGroups", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindAllUserGroups")
    @ResponseWrapper(localName = "findAllUserGroupsResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindAllUserGroupsResponse")
    public FindAllUserGroupsResult findAllUserGroups();

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.FindUserBindInfoByUserIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserBindInfoByUserId", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindUserBindInfoByUserId")
    @ResponseWrapper(localName = "findUserBindInfoByUserIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindUserBindInfoByUserIdResponse")
    public FindUserBindInfoByUserIdResult findUserBindInfoByUserId(
            @WebParam(name = "UserId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.FindUserBindInfoByUserIdResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUserBindInfoByUserIdV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindUserBindInfoByUserIdV2")
    @ResponseWrapper(localName = "findUserBindInfoByUserIdResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindUserBindInfoByUserIdResponseV2")
    public FindUserBindInfoByUserIdResultV2 findUserBindInfoByUserIdV2(
            @WebParam(name = "UserId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @return
     *     returns com.wifi.client.FindAllUserTemplatePackagesResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllUserTemplatePackages", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindAllUserTemplatePackages")
    @ResponseWrapper(localName = "findAllUserTemplatePackagesResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindAllUserTemplatePackagesResponse")
    public FindAllUserTemplatePackagesResult findAllUserTemplatePackages();

    /**
     * 
     * @param changeType
     * @param userId
     * @param packageId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePackage4Self", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ChangePackage4Self")
    @ResponseWrapper(localName = "changePackage4SelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ChangePackage4SelfResponse")
    public SamApiBaseResult changePackage4Self(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "packageId", targetNamespace = "")
                    String packageId,
            @WebParam(name = "changeType", targetNamespace = "")
                    String changeType);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.FindManagerInfoByIdResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findManagerInfoById", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindManagerInfoById")
    @ResponseWrapper(localName = "findManagerInfoByIdResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.FindManagerInfoByIdResponse")
    public FindManagerInfoByIdResult findManagerInfoById(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param noticeContent
     * @param deviceIps
     * @param noticeExpireTtime
     * @return
     *     returns com.wifi.client.SendMessageByDeviceResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageByDevice", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SendMessageByDevice")
    @ResponseWrapper(localName = "sendMessageByDeviceResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SendMessageByDeviceResponse")
    public SendMessageByDeviceResult sendMessageByDevice(
            @WebParam(name = "deviceIps", targetNamespace = "")
                    List<String> deviceIps,
            @WebParam(name = "noticeContent", targetNamespace = "")
                    String noticeContent,
            @WebParam(name = "noticeExpireTtime", targetNamespace = "")
                    XMLGregorianCalendar noticeExpireTtime);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInhibit", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddInhibit")
    @ResponseWrapper(localName = "addInhibitResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddInhibitResponse")
    public SamApiBaseResult addInhibit(
            @WebParam(name = "params", targetNamespace = "")
                    AddInhibitParams params);

    /**
     * 
     * @param params
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addInhibitV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddInhibitV2")
    @ResponseWrapper(localName = "addInhibitResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.AddInhibitResponseV2")
    public SamApiBaseResult addInhibitV2(
            @WebParam(name = "params", targetNamespace = "")
                    AddInhibitParamsV2 params);

    /**
     * 
     * @param param
     * @return
     *     returns com.wifi.client.QueryInhibitResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryInhibit", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryInhibit")
    @ResponseWrapper(localName = "queryInhibitResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryInhibitResponse")
    public QueryInhibitResult queryInhibit(
            @WebParam(name = "param", targetNamespace = "")
                    QueryInhibitParam param);

    /**
     * 
     * @param param
     * @return
     *     returns com.wifi.client.QueryInhibitResultV2
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryInhibitV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryInhibitV2")
    @ResponseWrapper(localName = "queryInhibitResponseV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.QueryInhibitResponseV2")
    public QueryInhibitResultV2 queryInhibitV2(
            @WebParam(name = "param", targetNamespace = "")
                    QueryInhibitParamV2 param);

    /**
     * 
     * @param uuid
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteInhibit", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DeleteInhibit")
    @ResponseWrapper(localName = "deleteInhibitResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.DeleteInhibitResponse")
    public SamApiBaseResult deleteInhibit(
            @WebParam(name = "uuid", targetNamespace = "")
                    String uuid);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperator", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperator")
    @ResponseWrapper(localName = "unbindOperatorResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorResponse")
    public SamApiBaseResult unbindOperator(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param operatorId
     * @param compusName
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperatorOfCompus", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorOfCompus")
    @ResponseWrapper(localName = "unbindOperatorOfCompusResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorOfCompusResponse")
    public SamApiBaseResult unbindOperatorOfCompus(
            @WebParam(name = "operatorId", targetNamespace = "")
                    String operatorId,
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName);

    /**
     * 
     * @param atName
     * @param userId
     * @param packageId
     * @param enableType
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "modifyUserPackageForSelf", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserPackageForSelf")
    @ResponseWrapper(localName = "modifyUserPackageForSelfResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.ModifyUserPackageForSelfResponse")
    public SamApiBaseResult modifyUserPackageForSelf(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "atName", targetNamespace = "")
                    String atName,
            @WebParam(name = "packageId", targetNamespace = "")
                    String packageId,
            @WebParam(name = "enableType", targetNamespace = "")
                    int enableType);

    /**
     * 
     * @param operatorName
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperator", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperator")
    @ResponseWrapper(localName = "rebindOperatorResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorResponse")
    public SamApiBaseResult rebindOperator(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param oldOperatorUserId
     * @param compusName
     * @param newOperatorUserId
     * @param newOperatorUserPassword
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rebindOperatorOfCompus", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorOfCompus")
    @ResponseWrapper(localName = "rebindOperatorOfCompusResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.RebindOperatorOfCompusResponse")
    public SamApiBaseResult rebindOperatorOfCompus(
            @WebParam(name = "oldOperatorUserId", targetNamespace = "")
                    String oldOperatorUserId,
            @WebParam(name = "compusName", targetNamespace = "")
                    String compusName,
            @WebParam(name = "newOperatorUserId", targetNamespace = "")
                    String newOperatorUserId,
            @WebParam(name = "newOperatorUserPassword", targetNamespace = "")
                    String newOperatorUserPassword);

    /**
     * 
     * @param operatorName
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bindOperator", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BindOperator")
    @ResponseWrapper(localName = "bindOperatorResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.BindOperatorResponse")
    public SamApiBaseResult bindOperator(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword);

    /**
     * 
     * @param operatorIp
     * @param userId
     * @param operatorUserPassword
     * @param operatorUserId
     * @param actType
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operatorHandle", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.OperatorHandle")
    @ResponseWrapper(localName = "operatorHandleResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.OperatorHandleResponse")
    public SamApiBaseResult operatorHandle(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorIp", targetNamespace = "")
                    String operatorIp,
            @WebParam(name = "operatorUserId", targetNamespace = "")
                    String operatorUserId,
            @WebParam(name = "operatorUserPassword", targetNamespace = "")
                    String operatorUserPassword,
            @WebParam(name = "actType", targetNamespace = "")
                    String actType);

    /**
     * 
     * @param operatorName
     * @param operatorId
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "unbindOperatorByParam", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorByParam")
    @ResponseWrapper(localName = "unbindOperatorByParamResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.UnbindOperatorByParamResponse")
    public SamApiBaseResult unbindOperatorByParam(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "operatorId", targetNamespace = "")
                    String operatorId,
            @WebParam(name = "operatorName", targetNamespace = "")
                    String operatorName);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspend4SelfPermission", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.Suspend4SelfPermission")
    @ResponseWrapper(localName = "suspend4SelfPermissionResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.Suspend4SelfPermissionResponse")
    public SamApiBaseResult suspend4SelfPermission(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param userId
     * @return
     *     returns com.wifi.client.SamApiBaseResult
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "resume4SelfPermission", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.Resume4SelfPermission")
    @ResponseWrapper(localName = "resume4SelfPermissionResponse", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.Resume4SelfPermissionResponse")
    public SamApiBaseResult resume4SelfPermission(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId);

    /**
     * 
     * @param message
     * @param userId
     * @param messageType
     * @return
     *     returns com.wifi.client.SendMessageV2Result
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sendMessageV2", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SendMessageV2")
    @ResponseWrapper(localName = "sendMessageV2Response", targetNamespace = "http://api.spl.ruijie.com/", className = "com.wifi.client.SendMessageV2Response")
    public SendMessageV2Result sendMessageV2(
            @WebParam(name = "userId", targetNamespace = "")
                    String userId,
            @WebParam(name = "message", targetNamespace = "")
                    String message,
            @WebParam(name = "messageType", targetNamespace = "")
                    int messageType);

}
